name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    permissions:
      contents: read
      actions: write

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses:  actions/checkout@v3

       # https://github.com/actions/setup-java
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build
        run: ./gradlew assembleDebug
