name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    permissions:
      contents: read
      actions: write

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses:  actions/checkout@v3

       # https://github.com/actions/setup-java
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Copy google-service.json
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assemble_devDebug
